{% set name = "ebcdic-parser" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ebcdic_parser-{{ version }}.tar.gz
  sha256: 568eb633b5000e3ad986b37d3954a4474734dcff8786372cb7606487ac7b63d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - pip
  run:
    - python >=3.7

test:
  imports:
    - ebcdic_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/larandvit/ebcdic-parser
  summary: Convert mainframe EBCDIC data into Unicode ASCII delimited text files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larandvit
    - rxm7706
